#!/bin/bash
# ==========================================
# Inicialización del MySQL Router
# ==========================================

# Bootstrap apuntando al nodo primario actual
sudo mysqlrouter --bootstrap clusteradmin@10.0.1.72:3306 --user=mysqlrouter

# Habilitar y arrancar el servicio de balanceo
sudo systemctl enable mysqlrouter
sudo systemctl start mysqlrouter
